version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  init:
    cmds:
    - cd infra && terraform init
  deploy:
    cmds:
    - cd infra && terraform apply
  destroy:
    - cd infra && terraform destroy

  invoke-gateway:
    cmds:
    - curl "$(cd infra && terraform output -raw base_url)/hello"

  setup:
    cmds:
    - task: init
    - task: deploy
    - task: invoke-gateway
