version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

env:
  TF_VAR_aws_access_key: "{{.AWS_ACCESS_KEY_ID}}"
  TF_VAR_aws_secret_key: "{{.AWS_SECRET_ACCESS_KEY}}"

tasks:
  infra-init:
    cmds:
    - cd hello-world && zip -r ../infra/hello-world.zip main.py
    - |
      cd {{.CLI_ARGS}} &&\
      bucket_name=$(aws s3api list-buckets --query 'Buckets[?starts_with(Name, `terraform-state`)].Name' --output text | tr -d ' \t\n') &&\
      terraform init \
        -backend-config="bucket=$bucket_name" \
        -backend-config="access_key={{ .AWS_ACCESS_KEY_ID }}" \
        -backend-config="secret_key={{ .AWS_SECRET_ACCESS_KEY }}" \
        -backend-config="region=us-east-1"

  main-infra-init:
    cmds:
    - terraform init

  deploy:
    cmds:
    - cd {{.CLI_ARGS}} && terraform apply
  destroy:
    - cd {{.CLI_ARGS}} && terraform destroy

  invoke-gateway:
    cmds:
    - curl $(aws apigatewayv2 get-apis --query 'Items[0].ApiEndpoint' --output text | tr -d ' \t\n')/serverless_lambda_stage/hello

  setup:
    cmds:
    - task: "{{.CLI_ARGS}}-init"
    - task: deploy
