version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

env:
  TF_VAR_aws_access_key: "{{.AWS_ACCESS_KEY_ID}}"
  TF_VAR_aws_secret_key: "{{.AWS_SECRET_ACCESS_KEY}}"

tasks:
  init:
    cmds:
    - cd main-infra && terraform init
  deploy:
    cmds:
    - cd main-infra && terraform apply
  destroy:
    - cd main-infra && terraform destroy

  invoke-gateway:
    cmds:
    - curl $(aws apigatewayv2 get-apis --query 'Items[0].ApiEndpoint' --output text | tr -d ' \t\n')/serverless_lambda_stage/hello

  setup:
    cmds:
    - task: init
    - task: deploy
